### ISSUE TITLE
Should analyses parameter types be genericized if they do not have a corresponding entry in postgres?

### ISSUE THREAD

**Issue by strootman** [cyverse-archive/metadactyl-clj#1]
A list of input property types are defined in [util.clj line 6](https://github.com/iPlantCollaborativeOpenSource/metadactyl-clj/blob/master/src/metadactyl/translations/app_metadata/util.clj#L6).

A list of output property types are defined in [util.clj line 9](https://github.com/iPlantCollaborativeOpenSource/metadactyl-clj/blob/master/src/metadactyl/translations/app_metadata/util.clj#L9).

These definitions are used in [util.clj line 56](https://github.com/iPlantCollaborativeOpenSource/metadactyl-clj/blob/master/src/metadactyl/translations/app_metadata/util.clj#L56). 

Since the "Input" and "Output" values no longer have corresponding values in the database, why are we using them here? 

I believe that this code directly relates to analysis parameters. So, if any analysis parameter type is a "FileInput" "FolderInput" or "MultiFileSelector", it is transformed into the generic "Input". 

I think it would be more correct to keep the parameter types as they are instead of genericizing them.

**Comment by slr71** [comment]
If I understand the question correctly, you're asking why the parameters are being translated from the specific input or output property types to just `Input` or `Output`. The only reason for that was speed of implementation; translating the property types involved only changing the export and import services, and changing the property types everywhere would also have required updates to the job submission services.

I like the idea of keeping the specific parameter types rather than genericizing them.

**Comment by strootman** [comment]
I assumed that there would be some other caveat.

This doesn't break/block anything on the UI, so it is a nice to have ATM.

**Comment by slr71** [comment]
No, there's no other caveat, just a large number of changes in the existing services and a high potential for breaking stuff.
